version: '3.8'
services:
  app5:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app5
    ports:
      - "8080:8080"
    depends_on:
      - db3
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db3:5432/movies
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true
  db3:
    container_name: db3
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movies
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
