version: '3.8'
services:
  pgsql:
    container_name: pgsql
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=movies
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
